export const FETCH_CARS = 'FETCH_CARS';
export const BOOK_CAR = 'BOOK_CAR';
export const FETCH_BOOKINGS = 'FETCH_BOOKINGS';
export const FETCH_RENTAL_CARS = "FETCH_RENTAL_CARS"
export const FETCH_USERS = "FETCH_USERS"
export const CREATE_CAR = "CREATE_CAR"
export const EDIT_CAR = "EDIT_CAR"
export const EDIT_USER = "EDIT_USER"
export const DELETE_CAR = "DELETE_CAR"

export const FETCH_REPORT = "FETCH_REPORT"

export const LOGIN = "LOGIN"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const SIGNUP = "SIGNUP"
export const SIGNUP_FAILED = "SIGNUP_FAILED"

export const CREATE_REPORT = "CREATE_REPORT"
export const FETCH_BOOKING_DATES = "FETCH_BOOKING_DATES"
export const FETCH_RETURN_DATES = "FETCH_RETURN_DATES"

export const FETCH_MOST_BOOKINGS = "FETCH_MOST_BOOKINGS"
export const FETCH_LEAST_BOOKINGS = "FETCH_LEAST_BOOKINGS"
export const FETCH_MOST_REVENUES = "FETCH_MOST_REVENUES"